---
- name: install default flatpaks as user-managed flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
    method: system
  loop:
    - org.signal.Signal
    - us.zoom.Zoom
    - com.discordapp.Discord
    - org.kde.kdenlive
    - org.glimpse_editor.Glimpse
    - org.zotero.Zotero
    - com.slack.Slack
    - com.spotify.Client
    - org.chromium.Chromium
    - org.mozilla.Thunderbird
    - md.obsidian.Obsidian
    - org.telegram.desktop
