---
- include_tasks: misc.yml
- include_tasks: user-management.yml
- include_tasks: packages.yml
- include_tasks: flatpaks.yml
- include_tasks: theme.yml
- include_tasks: displaylink.yml
- include_tasks: cursor.yml