---
- name: synchronize fossbook.nolski.io
  hosts: workstation
  become: yes

  vars:
    target_group: nolski
    target_user: nolski
    target_user_name: Mike Nolan
    user_home_dir: /home/nolski

  roles:
    - { role: system/base, tags: ['base', 'system'] }
    - { role: system/fedora-workstation, tags: ['fedora', 'system'] }
    - { role: system/packaging-tools, tags: ['packaging-tools', 'system'] }
    - { role: system/python, tags: ['python', 'system'] }
    - { role: system/ruby, tags: ['ruby', 'system'] }
    - { role: apps/bash, tags: ['bash', 'terminal', 'apps'] }
    - { role: apps/git, tags: ['git', 'terminal', 'apps'] }
    - { role: apps/npm, tags: ['npm', 'terminal', 'apps'] }
    - { role: apps/powerline-go, tags: ['powerline', 'terminal', 'apps'] }
    - { role: apps/slack, tags: ['slack', 'desktop', 'apps'] }
    - { role: apps/spotify, tags: ['spotify', 'desktop', 'apps'] }
    - { role: apps/ssh, tags: ['ssh', 'terminal', 'apps'] }
    - { role: apps/thunderbird, tags: ['thunderbird', 'desktop', 'apps'] }
    - { role: apps/tmux, tags: ['tmux', 'terminal', 'apps'] }
    - { role: apps/vim, tags: ['vim', 'terminal', 'apps'] }
